OnlineTeknololoji/Controllers/AdminController.cs
using Newtonsoft.Json;
using OnlineTeknololoji.DAL1;
using OnlineTeknololoji.Models;
using OnlineTeknololoji.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace OnlineTeknololoji.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();
        
        public List<SelectListItem> GetCategory()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            var cat = _unitOfWork.GetRepositoryInstance<OnlineTeknololoji.DAL1.KategoriTablo>().GetAllRecords();
            foreach(var item in cat)
            {
                list.Add(new SelectListItem { Value = item.KategoriId.ToString(), Text = item.KategoriIsim });
            }
            return list;
        }
        public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult Categories()
        {
            List<OnlineTeknololoji.DAL1.KategoriTablo> allcategories = _unitOfWork.GetRepositoryInstance<OnlineTeknololoji.DAL1.KategoriTablo>().GetAllRecordsIQueryable().Where(i => i.SilindiMi == false).ToList();
            return View(allcategories);
        }
        public ActionResult AddCategory()
        {
            return UpdateCategory(0);
        }
        public ActionResult UpdateCategory(int categoryId)
        {
            CategoryDetail cd;
            if (categoryId != null)
            {
                cd = JsonConvert.DeserializeObject<OnlineTeknololoji.Models.CategoryDetail>(JsonConvert.SerializeObject(_unitOfWork.GetRepositoryInstance<OnlineTeknololoji.DAL1.KategoriTablo>().GetFirstorDefault(categoryId)));
            }
            else
            {
                cd = new CategoryDetail();
            }
            return View("UpdateCategory",cd);
        }
        public ActionResult CategoryEdit(int catId)
        {
            return View(_unitOfWork.GetRepositoryInstance<OnlineTeknololoji.DAL1.KategoriTablo>().GetFirstorDefault(catId));
        }
        [HttpPost]
        public ActionResult CategoryEdit(KategoriTablo table)
        {
            _unitOfWork.GetRepositoryInstance<KategoriTablo>().Update(table);
            return RedirectToAction("Categories");
        }
        public ActionResult Product()
        {
            return View(_unitOfWork.GetRepositoryInstance<OnlineTeknololoji.DAL1.UrunTablo>().GetProduct());
        }
        public ActionResult ProductEdit(int productId)
        {
            ViewBag.CategoryList = GetCategory();
            return View(_unitOfWork.GetRepositoryInstance<OnlineTeknololoji.DAL1.UrunTablo>().GetFirstorDefault(productId));
        }
        [HttpPost]
        public ActionResult ProductEdit(UrunTablo table, HttpPostedFileBase file)
        {
            string pic = null;
            if (file != null)
            {
                pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/ProductImage/"), pic);
                // dosya yüklendi
                file.SaveAs(path);
            }
            table.UrunFoto = file != null ? pic : table.UrunFoto;
            table.DegistirilmeTarihi = DateTime.Now;
            _unitOfWork.GetRepositoryInstance<UrunTablo>().Update(table);
            return RedirectToAction("Product");
        }
        public ActionResult ProductAdd()
        {
            ViewBag.CategoryList = GetCategory();
            return View();
        }
        [HttpPost]
        public ActionResult ProductAdd(UrunTablo table, HttpPostedFileBase file)
        {
            string pic =null;
            if (file != null)
            {
                pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/ProductImage/"), pic);
                // dosya yüklendi
                file.SaveAs(path);
            }
            table.UrunFoto = pic;
            table.OlusturmaTarihi = DateTime.Now;
            _unitOfWork.GetRepositoryInstance<UrunTablo>().Add(table);
            return RedirectToAction("Product");
        }
    }
}

OnlineTeknololoji/Views/Admin/Categories.cshtml
@model List<OnlineTeknololoji.DAL1.KategoriTablo>
@{
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Categories</li>
    </ol>
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Category Details
            <a href="../Admin/AddCategory" class="btn btn-info pull-right fa fa-plus">Yeni Ekle</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Sr. No.</th>
                            <th>Category Name</th>
                            <th>Action</th>

                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Sr. No.</th>
                            <th>Category Name</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>@(Model.IndexOf(item)+1)</td>
                                <td>@item.KategoriIsim</td>
                                <td>
                                    @Html.ActionLink("Edit", "CategoryEdit", new { catId = item.KategoriId })
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

OnlineTeknololoji/Views/Admin/CategoryEdit.cshtml
@model OnlineTeknololoji.DAL1.KategoriTablo
@{
    ViewBag.Title = "ProductAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
    <div class="container">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Kategori</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.KategoriId)
            <div class="form-group">
                @Html.LabelFor(model => model.KategoriIsim, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KategoriIsim, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KategoriIsim, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AktifMi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AktifMi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AktifMi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SilindiMi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SilindiMi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SilindiMi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
        }
    </div>

OnlineTeknololoji/Views/Admin/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Dashboard</h2>

OnlineTeknololoji/Views/Admin/Product.cshtml
@model IEnumerable<OnlineTeknololoji.DAL1.UrunTablo>

@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Product</h2>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Product Details
        <a href="../Admin/ProductAdd" class="btn btn-info pull-right fa fa-plus">Yeni Ekle</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Sr. No.</th>
                        <th>Product Name</th>
                        <th>Action</th>

                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Sr. No.</th>
                        <th>Product Name</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        int count = 1;
                        <tr>
                            <td>@count</td>
                            <td>@item.UrunIsim</td>
                            <td>
                            @Html.ActionLink("Edit", "ProductEdit", new { productId = item.UrunId })
                            </td>

                        </tr>
                        count++;
                    }

                </tbody>
            </table>
        </div>

    </div>
</div>

OnlineTeknololoji/Views/Admin/ProductAdd.cshtml
@model OnlineTeknololoji.DAL1.UrunTablo

@{
    ViewBag.Title = "ProductAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
    <div class="container">

        @using (Html.BeginForm("ProductAdd", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Urun</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UrunIsim, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UrunIsim, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UrunIsim, "", new { @class = "text-danger" })
                </div>
            </div>
            @{
                List<SelectListItem> data = ViewBag.CategoryList;
            }
          
                <div class="form-group">
                    @Html.LabelFor(model => model.KategoriId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.KategoriId, data, "Seç", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                    </div>
                </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AktifMi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AktifMi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AktifMi, "", new { @class = "text-danger" })
                </div>
            </div>
            @Html.HiddenFor(model => model.SilindiMi)
            
            <div class="form-group">
                @Html.LabelFor(model => model.UrunFoto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="file" id="file" style="width: 100%;" />
                    @Html.ValidationMessageFor(model => model.UrunFoto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OzellikliMi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OzellikliMi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OzellikliMi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Miktar, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Miktar, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Miktar, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
        }

    </div>

OnlineTeknololoji/Views/Admin/ProductEdit.cshtml
@model OnlineTeknololoji.DAL1.UrunTablo

@{
    ViewBag.Title = "ProductAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("ProductEdit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Ürün</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.UrunId, new { htmlAttributes = new { @class = "form-control" } })
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.UrunIsim, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.UrunIsim, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.UrunIsim, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @{
                    List<SelectListItem> data = ViewBag.CategoryList;
                }
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.KategoriId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.KategoriId, data, "Seç", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.AktifMi, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AktifMi, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.AktifMi, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.SilindiMi, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SilindiMi, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SilindiMi, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                @Html.HiddenFor(model => model.OlusturmaTarihi)

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.UrunFoto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="file" id="file" style="width: 100%;" />
                            @Html.ValidationMessageFor(model => model.UrunFoto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">

                    <div class="form-group">
                        @Html.LabelFor(model => model.OzellikliMi, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.OzellikliMi, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.OzellikliMi, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Miktar, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Miktar, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Miktar, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}

OnlineTeknololoji/Views/Admin/UpdateCategory.cshtml
@model OnlineTeknololoji.Models.CategoryDetail
@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Dashboard</a>
            </li>
            <li class="breadcrumb-item">Categories</li>
            <li class="breadcrumb-item active">Add New Category</li>
        </ol>
        <!-- DataTables Example -->
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Add New Category
            </div>
            <div class="card-body">
                @using(Html.BeginForm("UpdateCategory", "Admin", FormMethod.Post, new { enctype="multipart/form-data"}))
                {   
                @Html.HiddenFor(m => m.KategoriId)
                <div class="form-group">
                    <label class="control-label">Category Name</label>
                    @Html.TextBoxFor(m => m.KategoriIsim, new { @class = "form-control", placeholder="Enter category Name", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(m => m.KategoriIsim, "", new{@class="text-danger"})
                </div>
                <a onclick="window.history.back();" class="btn btn-danger">Cancel</a>
                <input type="submit" class="btn btn-primary" value="Save"/>
                }
            </div>
        </div>
    </div>